groups:
- name: SupabaseAlerts
  rules:
  - alert: SupabaseInstanceDown
    expr: up{job="supabase"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Supabase instance down"
      description: "Supabase instance has been down for more than 1 minute\n Instance: {{ $labels.instance }}"

  - alert: SupabaseHighConnections
    expr: sum by (instance) (pg_stat_activity_count) > (pg_settings_max_connections * 0.8)
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High number of Supabase connections"
      description: "Supabase instance has more than 80% of connections used\n Instance: {{ $labels.instance }}\n Value: {{ $value }}"

  - alert: SupabaseAuthFailures
    expr: rate(supabase_auth_failures_total[5m]) > 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High rate of authentication failures"
      description: "Supabase is experiencing high rate of auth failures\n Instance: {{ $labels.instance }}\n Value: {{ $value }}"

  - alert: SupabaseStorageErrors
    expr: rate(supabase_storage_errors_total[5m]) > 5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Supabase storage errors detected"
      description: "High rate of storage errors in Supabase\n Instance: {{ $labels.instance }}\n Value: {{ $value }}"

  - alert: SupabaseRealtimeConnections
    expr: supabase_realtime_connections > 1000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High number of realtime connections"
      description: "Supabase realtime connections exceeding threshold\n Instance: {{ $labels.instance }}\n Value: {{ $value }}"

  - alert: SupabaseEdgeFunctionErrors
    expr: rate(supabase_edge_function_errors_total[5m]) > 5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Edge Function errors detected"
      description: "High rate of Edge Function errors\n Instance: {{ $labels.instance }}\n Value: {{ $value }}"

  - alert: SupabaseHighLatency
    expr: rate(supabase_http_request_duration_seconds_sum[5m]) / rate(supabase_http_request_duration_seconds_count[5m]) > 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High API latency detected"
      description: "Supabase API latency is above 1 second\n Instance: {{ $labels.instance }}\n Value: {{ $value }}"

  - alert: SupabaseDiskSpaceCritical
    expr: (1 - (node_filesystem_avail_bytes{mountpoint=~"/.*"} / node_filesystem_size_bytes{mountpoint=~"/.*"})) * 100 > 85
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Supabase disk space critical"
      description: "Supabase disk space usage is above 85%\n Instance: {{ $labels.instance }}\n Mount point: {{ $labels.mountpoint }}\n Value: {{ $value }}%"

  - alert: SupabaseHighCPUUsage
    expr: rate(process_cpu_seconds_total{job="supabase"}[5m]) > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Supabase high CPU usage"
      description: "Supabase CPU usage is above 80%\n Instance: {{ $labels.instance }}\n Value: {{ $value }}%"

  - alert: SupabasePostgRESTErrors
    expr: rate(postgrest_error_total[5m]) > 5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "PostgREST errors detected"
      description: "High rate of PostgREST errors in Supabase\n Instance: {{ $labels.instance }}\n Value: {{ $value }}"

  - alert: SupabaseGotTrueErrors
    expr: rate(gotrue_error_total[5m]) > 5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "GoTrue auth errors detected"
      description: "High rate of GoTrue authentication errors\n Instance: {{ $labels.instance }}\n Value: {{ $value }}" 