groups:
- name: MongoDBAlerts
  rules:
  - alert: MongoDBInstanceDown
    expr: mongodb_up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "MongoDB instance down"
      description: "MongoDB instance has been down for more than 1 minute\n Instance: {{ $labels.instance }}"

  - alert: MongoDBReplicationLag
    expr: mongodb_ss_metrics_repl_network_getmores_totalMillis > 300000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MongoDB replication lag"
      description: "MongoDB replication is experiencing high latency\n Instance: {{ $labels.instance }}\n Value: {{ $value }}ms"

  - alert: MongoDBReplicationErrors
    expr: rate(mongodb_ss_metrics_repl_network_notPrimaryUnacknowledgedWrites[5m]) > 0 or rate(mongodb_ss_metrics_repl_syncSource_numTimesCouldNotFind[5m]) > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MongoDB replication errors"
      description: "MongoDB replication is experiencing errors\n Instance: {{ $labels.instance }}"

  - alert: MongoDBHighConnections
    expr: mongodb_ss_connections{conn_type="current"} > (mongodb_ss_connections{conn_type="available"} * 0.8)
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MongoDB high connection usage"
      description: "MongoDB is using more than 80% of available connections\n Instance: {{ $labels.instance }}"

  - alert: MongoDBHighLatency
    expr: rate(mongodb_ss_metrics_commands_replSetGetConfig_failed[5m]) > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MongoDB high operation latency"
      description: "MongoDB operations are experiencing failures\n Instance: {{ $labels.instance }}"

  - alert: MongoDBReplicationBufferIssues
    expr: mongodb_ss_metrics_repl_buffer_write_sizeBytes > mongodb_ss_metrics_repl_buffer_write_maxSizeBytes * 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MongoDB replication buffer issues"
      description: "MongoDB replication buffer is near capacity\n Instance: {{ $labels.instance }}"

  - alert: MongoDBDiskSpaceCritical
    expr: (1 - (node_filesystem_avail_bytes{mountpoint=~"/.*"} / node_filesystem_size_bytes{mountpoint=~"/.*"})) * 100 > 85
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "MongoDB disk space critical"
      description: "MongoDB disk space usage is above 85%\n Instance: {{ $labels.instance }}\n Mount point: {{ $labels.mountpoint }}\n Value: {{ $value }}%"

  - alert: MongoDBHighCPUUsage
    expr: rate(process_cpu_seconds_total{job="mongodb"}[5m]) > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MongoDB high CPU usage"
      description: "MongoDB CPU usage is above 80%\n Instance: {{ $labels.instance }}\n Value: {{ $value }}%"

  - alert: MongoDBReplicationStateTransition
    expr: rate(mongodb_ss_metrics_repl_stateTransition_totalOperationsKilled[5m]) > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MongoDB replication state transition issues"
      description: "MongoDB replication state transitions are causing operation kills\n Instance: {{ $labels.instance }}"

  - alert: MongoDBInitialSyncFailures
    expr: rate(mongodb_ss_metrics_repl_initialSync_failures[5m]) > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MongoDB initial sync failures"
      description: "MongoDB is experiencing initial sync failures\n Instance: {{ $labels.instance }}" 