groups:
- name: MongoDBAlerts
  rules:
  - alert: MongoDBInstanceDown
    expr: mongodb_up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "MongoDB instance down"
      description: "MongoDB instance has been down for more than 1 minute\n Instance: {{ $labels.instance }}"

  - alert: MongoDBReplicationLag
    expr: mongodb_mongod_replset_member_optime_date{state="SECONDARY"} - on(set) group_right mongodb_mongod_replset_member_optime_date{state="PRIMARY"} > 60
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MongoDB replication lag"
      description: "MongoDB replication lag is more than 60 seconds\n Instance: {{ $labels.instance }}\n Value: {{ $value }} seconds"

  - alert: MongoDBHighConnections
    expr: mongodb_connections{state="current"} > mongodb_connections{state="available"} * 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MongoDB high connection usage"
      description: "MongoDB is using more than 80% of available connections\n Instance: {{ $labels.instance }}"

  - alert: MongoDBHighLatency
    expr: rate(mongodb_op_latencies_latency_total[5m]) / rate(mongodb_op_latencies_ops_total[5m]) > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MongoDB high operation latency"
      description: "MongoDB operations are experiencing high latency\n Instance: {{ $labels.instance }}"

  - alert: MongoDBWTCacheEvictions
    expr: rate(mongodb_wiredtiger_cache_evicted_total[5m]) > 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MongoDB WiredTiger cache evictions"
      description: "High rate of WiredTiger cache evictions\n Instance: {{ $labels.instance }}"

  - alert: MongoDBPageFaults
    expr: rate(mongodb_extra_info_page_faults_total[5m]) > 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MongoDB page faults"
      description: "High rate of page faults\n Instance: {{ $labels.instance }}"

  - alert: MongoDBDiskSpaceCritical
    expr: (1 - (node_filesystem_avail_bytes{mountpoint=~"/.*"} / node_filesystem_size_bytes{mountpoint=~"/.*"})) * 100 > 85
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "MongoDB disk space critical"
      description: "MongoDB disk space usage is above 85%\n Instance: {{ $labels.instance }}\n Mount point: {{ $labels.mountpoint }}\n Value: {{ $value }}%"

  - alert: MongoDBHighCPUUsage
    expr: rate(process_cpu_seconds_total{job="mongodb"}[5m]) > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MongoDB high CPU usage"
      description: "MongoDB CPU usage is above 80%\n Instance: {{ $labels.instance }}\n Value: {{ $value }}%"

  - alert: MongoDBCursorTimeout
    expr: rate(mongodb_metrics_cursor_timed_out_total[5m]) > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MongoDB cursor timeouts"
      description: "MongoDB is experiencing cursor timeouts\n Instance: {{ $labels.instance }}"

  - alert: MongoDBAssertRegular
    expr: rate(mongodb_asserts_total{type="regular"}[5m]) > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MongoDB regular assertions"
      description: "MongoDB is reporting regular assertions\n Instance: {{ $labels.instance }}" 